# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-I18N-DBIC
version:      0.01
version_from: DBIC.pm
installdirs:  site
requires:
    Catalyst:                       2.99
    Catalyst-Plugin-I18N-DBIC:      0
    Catalyst-Plugin-DBIC:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
